trigger:
- development

resources:
  repositories:
    - repository: templates
      type: git
      name: Fabric/Pipeline

stages:
  - stage: Build
    jobs:
    - template: BuildLibrary.yml@templates
      parameters:
        packagesToPack: '**/Serialization.*.csproj'
        
  - stage: Publish
    jobs:
    - template: PublishToArtifacts.yml@templates
